### ISSUE TITLE
Keytar error

### ISSUE THREAD

**Issue by tienzodi** [thundernet8/StarCabinet#11]
Hello,
I got issue below when I try to run npm start
![image](https://user-images.githubusercontent.com/21222786/30632535-a6773e00-9e12-11e7-84e2-0ff15b9c30a8.png)
How can I fix it ? Thank  you

**Comment by thundernet8** [comment]
try 
npm install windows-build-tools -g

**Comment by tienzodi** [comment]
let me try it. thx.

**Comment by tienzodi** [comment]
it doesn't work on my computer. I got same issue on my macbook :|

**Comment by thundernet8** [comment]
@tienzodi or try 
```
npm rebuild
```
to rebuild keytar.node module

**Comment by tienzodi** [comment]
I'm trying to do that

**Comment by etgundam53** [comment]
use npm rebuild，There are still problems。
App threw an error during load
Error: Cannot open D:\Microsoft VS Code\workspace\StarCabinet-master\node_modules\keytar\build\Release\keytar.node: Error: A dynamic link library (DLL) initialization routine failed.

**Comment by thundernet8** [comment]
@etgundam53 [Keytar](https://github.com/atom/node-keytar/issues/51)

So try to upgrade keytar package
```
npm remove keytar
npm install keytar
```

**Comment by etgundam53** [comment]
i try ，npm remove keytar， npm install keytar  ，Still wrong
App threw an error during load
Error: Cannot open D:\Microsoft VS Code\workspace\StarCabinet-master\node_modules\keytar\build\Release\keytar.node: Error: A dynamic link library (DLL) initialization routine failed.

system  win10

**Comment by thundernet8** [comment]
@etgundam53 which version of node do you have?

delete node_modules folder and reinstall packages
after you run `npm install`, try
```
./node_modules/.bin/electron-rebuild

# On Windows if you have trouble, try:
.\node_modules\.bin\electron-rebuild.cmd
```

**Comment by thundernet8** [comment]
Feel free to reopen it if needed

**Comment by MichalJakubeczy** [comment]
For me (Windows) following worked:
- open console as Administrator,
- run `.\node_modules\.bin\electron-rebuild.cmd`
