### ISSUE TITLE
关于dist 目录的一些疑问

### ISSUE THREAD

**Issue by waltcow** [thundernet8/StarCabinet#6]
你好，最近在研究你的项目，有些地方不是很明白想请教一下。
这个文件 [app/package.json](https://github.com/thundernet8/StarCabinet/blob/master/app/package.json) 声明的`dependencies`是不是有的多余了？依赖在外面已经安装了，webpack build完的文件放在app/dist/ 下，无需再次安装吧？

**Comment by thundernet8** [comment]
@waltcow 
https://github.com/electron-userland/electron-builder/wiki/Two-package.json-Structure

**Comment by waltcow** [comment]
明白了，谢谢🙏
