### ISSUE TITLE
登陆页面无法paste内容到输入框

### ISSUE THREAD

**Issue by waltcow** [thundernet8/StarCabinet#7]
mac下登陆页面无法paste内容到输入框
类似问题：https://github.com/electron/electron/issues/4107
解决方法：https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by thundernet8** [comment]
@waltcow 
我试了没有这个问题，可以支持commond+v粘贴内容到输入框，我是最新的mac os sierra

**Comment by thundernet8** [comment]
这个后面细化的时候再添加，目前还是主要在做渲染UI

**Comment by thundernet8** [comment]
已解决
