### ISSUE TITLE
rxdb Schema 中的出现typo，导致数据验证出现异常

### ISSUE THREAD

**Issue by waltcow** [thundernet8/StarCabinet#8]
rxdb下面的schema中 *boolean*的拼写出现问题，有的是*bool*，有点是*boolen*，导致数据校验时出现异常

**Comment by thundernet8** [comment]
具体报错是什么，我这边没有错误也没有警告

**Comment by waltcow** [comment]
<img width="818" alt="screen shot 2017-03-18 at 1 40 51 pm" src="https://cloud.githubusercontent.com/assets/3941174/24069337/9980660a-0be0-11e7-8807-ec07843c48d1.png">

**Comment by thundernet8** [comment]
已全部更改为bool

**Comment by thundernet8** [comment]
我用Travis-CI打包的出现bool类型错误，现全部改为boolen

**Comment by thundernet8** [comment]
@waltcow 
是我的拼写错误，应该是boolean，不是boolen

<img width="333" alt="schema-types" src="https://cloud.githubusercontent.com/assets/7200477/24072305/5f191634-0c20-11e7-87a7-c1f273af1bfa.png">
